begin;
select plan(69);

select has_table('public','business_locations','canonical location identities exist');
select has_table('public','catalog_items','canonical catalog items exist');
select has_table('public','domain_source_mappings','provider identifiers map to internal entities');
select has_table('public','financial_events','normalized financial events exist');
select has_table('public','financial_event_lines','financial event lines exist');
select has_table('public','action_proposals','transactional action proposals exist');
select has_table('public','action_approval_decisions','approval decisions are stored separately');
select has_table('public','action_execution_records','execution attempts are recorded');
select has_table('public','square_inventory_count_observations','Square inventory counts retain append-only observations');
select has_table('public','external_identity_mappings','Teams identities can map to organization members');
select has_column('public','memberships','custom_role_id','members can use a custom role');
select has_column('public','memberships','location_scope_mode','members can be scoped to locations');
select has_column('public','audit_events','source_message_ref','audit records can link to a source message');
select has_column('public','audit_events','originating_automation','audit records can identify automation provenance');
select has_column('public','audit_events','execution_status','audit records retain execution outcome');
select has_column('public','action_approval_policies','amount_currency','approval thresholds are bound to a currency');
select has_column('public','action_approval_decisions','decided_by_kind','system expiry is not misattributed to a user');
select has_function('public','has_organization_permission',array['uuid','text','uuid'],'permission checks are available to authenticated API callers');
select has_function('public','list_financial_events',array['uuid','timestamp with time zone','timestamp with time zone'],'financial event read API is available');
select has_function('public','materialize_square_financial_events',array['uuid'],'Square facts materialize to events');
select has_function('public','get_product_analytics_facts_authorized',array['uuid','timestamp with time zone','timestamp with time zone'],'analytics data uses a permission-gated RPC');
select has_function('public','get_product_catalog_items_authorized',array['uuid'],'catalog costs use a permission-gated RPC');
select has_function('public','get_inventory_snapshot_authorized',array['uuid','timestamp with time zone','timestamp with time zone','text'],'inventory snapshots use a permission-gated RPC');
select has_function('public','propose_action',array['uuid','text','jsonb','text','uuid','bigint','text','jsonb','text','text','text','uuid'],'actions are proposed transactionally');
select has_function('public','decide_action',array['uuid','uuid','text','text','text','text'],'approval decisions use an idempotent RPC');
select has_function('private','action_source_version_matches',array['uuid','text','jsonb','text'],'catalog actions validate their exact source mapping and version');
select has_function('public','get_square_inventory_counts',array['uuid'],'Square count reads are permission gated');
select has_function('public','get_square_inventory_targets_system',array['uuid'],'worker can list mapped Square inventory targets');
select has_function('public','upsert_square_inventory_counts',array['uuid','jsonb'],'worker can persist source count snapshots');
select has_function('public','set_action_approval_policy',array['uuid','text','uuid','text','bigint','bigint','text','text','integer','bigint'],'policy thresholds use an explicit currency');
select has_function('public','cancel_action_proposal',array['uuid','uuid','text','text'],'pending actions can be cancelled with a reason');
select has_function('public','expire_action_proposals_system',array['uuid','integer'],'expired proposals can be terminalized by the worker');
select has_function('public','set_teams_identity',array['uuid','uuid','uuid','uuid','text','boolean','text'],'Teams identity links are permission-checked and audited');
select ok((select relrowsecurity from pg_class where oid='public.financial_events'::regclass),'financial events use row-level security');
select ok((select relrowsecurity from pg_class where oid='public.domain_source_mappings'::regclass),'source mappings use row-level security');
select ok((select relrowsecurity from pg_class where oid='public.action_proposals'::regclass),'action proposals use row-level security');
select ok((select relrowsecurity from pg_class where oid='public.square_inventory_count_observations'::regclass),'Square count observations use row-level security');
select ok(not has_table_privilege('authenticated','public.inventory_movements','SELECT'),'inventory movement table select is not granted broadly');
select ok(has_column_privilege('authenticated','public.inventory_movements','quantity_delta','SELECT'),'employees can read inventory quantities');
select ok(not has_column_privilege('authenticated','public.inventory_movements','unit_cost_minor','SELECT'),'inventory acquisition costs are not exposed by table select');
select ok(not has_function_privilege('authenticated','public.get_product_analytics_facts(uuid,timestamptz,timestamptz)','EXECUTE'),'membership-only analytics RPC is no longer callable');
select ok(not has_function_privilege('authenticated','public.get_product_catalog_items(uuid)','EXECUTE'),'membership-only product catalog RPC is no longer callable');
select ok(not has_function_privilege('authenticated','public.get_inventory_snapshot(uuid,timestamptz,timestamptz,text)','EXECUTE'),'membership-only inventory RPC is no longer callable');
select ok(has_function_privilege('authenticated','public.get_product_analytics_facts_authorized(uuid,timestamptz,timestamptz)','EXECUTE'),'authenticated users can call the gated analytics RPC');
select ok(has_function_privilege('authenticated','public.get_inventory_snapshot_authorized(uuid,timestamptz,timestamptz,text)','EXECUTE'),'authenticated users can call the gated inventory RPC');
select ok(has_function_privilege('authenticated','public.list_financial_events(uuid,timestamptz,timestamptz)','EXECUTE'),'authenticated users can call the gated event ledger');
select ok(position('approved_action.execute' in (select pg_get_constraintdef(oid) from pg_constraint where conrelid='private.durable_jobs'::regclass and conname='durable_jobs_job_type_check'))>0,'approved action executions can use the durable queue');
select ok(exists(select 1 from pg_trigger where tgrelid='public.cash_movements'::regclass and tgname='cash_movements_financial_event' and not tgisinternal),'cash activity materializes to the event ledger');
select ok(exists(select 1 from pg_trigger where tgrelid='public.inventory_movements'::regclass and tgname='inventory_movements_financial_event' and not tgisinternal),'inventory acquisitions materialize to the event ledger');
select ok(exists(select 1 from pg_trigger where tgrelid='public.financial_events'::regclass and tgname='financial_events_append_only' and not tgisinternal),'financial event rows are append-only');
select ok(exists(select 1 from pg_trigger where tgrelid='public.financial_event_lines'::regclass and tgname='financial_event_line_currency_guard' and not tgisinternal),'financial event lines cannot mix currencies with their parent');
select ok(exists(select 1 from pg_trigger where tgrelid='public.action_approval_decisions'::regclass and tgname='action_approval_decisions_append_only' and not tgisinternal),'approval decisions are append-only');
select ok(exists(select 1 from pg_trigger where tgrelid='public.action_proposals'::regclass and tgname='action_proposal_update_guard' and not tgisinternal),'proposal payloads and state transitions are guarded');
select ok(exists(select 1 from pg_trigger where tgrelid='public.action_execution_records'::regclass and tgname='action_execution_record_update_guard' and not tgisinternal),'execution state transitions are guarded');
select ok(exists(select 1 from pg_trigger where tgrelid='public.action_execution_records'::regclass and tgname='action_execution_records_no_delete' and not tgisinternal),'execution records cannot be deleted');
select ok(not has_function_privilege('authenticated','public.materialize_square_financial_events(uuid)','EXECUTE'),'financial event materialization is worker-only');
select ok(has_function_privilege('authenticated','public.get_square_inventory_counts(uuid)','EXECUTE'),'members can call the gated Square inventory count RPC');
select ok(not has_function_privilege('authenticated','public.upsert_square_inventory_counts(uuid,jsonb)','EXECUTE'),'Square inventory writes are worker-only');
select ok(not has_function_privilege('authenticated','public.get_square_inventory_targets_system(uuid)','EXECUTE'),'Square inventory target listing is worker-only');
select ok(exists(select 1 from pg_trigger where tgrelid='public.square_inventory_count_observations'::regclass and tgname='square_inventory_count_observations_append_only' and not tgisinternal),'Square source count observations are append-only');
select has_table('public','domain_command_idempotency','domain writes have durable idempotency records');
select has_column('public','purchase_orders','location_id','purchase orders are scoped to a Vernius location');
select has_function('public','create_domain_catalog_item',array['uuid','jsonb','text','text'],'Vernius catalog drafts use an authenticated command');
select has_function('public','list_domain_purchase_orders',array['uuid','integer'],'purchase orders have a permission-filtered read');
select has_function('public','create_domain_purchase_order',array['uuid','jsonb','text','text'],'purchase orders use an authenticated command');
select ok(has_function_privilege('authenticated','public.create_domain_catalog_item(uuid,jsonb,text,text)','EXECUTE'),'authenticated callers can create permission-gated catalog drafts');
select ok(has_function_privilege('authenticated','public.list_domain_purchase_orders(uuid,integer)','EXECUTE'),'authenticated callers can list location-filtered purchase orders');
select ok(has_function_privilege('authenticated','public.create_domain_purchase_order(uuid,jsonb,text,text)','EXECUTE'),'authenticated callers can create permission-gated purchase orders');
select ok(not has_table_privilege('authenticated','public.domain_command_idempotency','SELECT'),'idempotency response records are not directly readable');

select * from finish();
rollback;
